import type { CSSProperties } from "react";
import { mono } from "./constants";

export const grid2: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px,1fr))", gap: "0 20px" };
export const labelTxt: CSSProperties = { fontSize: 13, fontWeight: 600, color: "var(--ink-soft)" };
export const input: CSSProperties = { height: 44, padding: "0 14px", borderRadius: 10, border: "1px solid var(--line)", background: "var(--bg)", color: "var(--ink)", fontSize: 15, width: "100%" };
export const hint: CSSProperties = { fontSize: 12.5, color: "var(--ink-faint)", marginTop: 2 };
export const avisoBox: CSSProperties = { padding: "12px 16px", borderRadius: 10, fontSize: 14, marginTop: 12 };
export const cardBtn: CSSProperties = { display: "flex", flexDirection: "column", gap: 6, alignItems: "flex-start", padding: 16, borderRadius: 14, border: "1px solid var(--line)", background: "var(--surface)", cursor: "pointer", textAlign: "left" };
export const pill: CSSProperties = { fontSize: 10.5, fontFamily: mono, textTransform: "uppercase", letterSpacing: "0.06em", padding: "2px 8px", borderRadius: 100, background: "var(--warm-wash)", color: "var(--warm)" };
export const chip: CSSProperties = { padding: "8px 14px", borderRadius: 100, border: "1px solid var(--line)", background: "var(--surface)", color: "var(--ink-soft)", fontSize: 13.5, fontWeight: 500, cursor: "pointer" };
export const chipOn: CSSProperties = { border: "1px solid var(--cool)", background: "var(--cool-wash)", color: "var(--cool-deep)", fontWeight: 600 };
export const cartaoAmbiente: CSSProperties = { padding: "18px 20px", borderRadius: 14, border: "1px solid var(--line)", background: "var(--surface)" };
export const selo: CSSProperties = { display: "grid", placeItems: "center", width: 28, height: 28, borderRadius: "50%", background: "var(--cool)", color: "#fff", fontFamily: mono, fontSize: 13, fontWeight: 700, flexShrink: 0 };
export const btnRemover: CSSProperties = { height: 44, padding: "0 14px", borderRadius: 10, background: "transparent", color: "var(--ink-faint)", fontSize: 13.5, fontWeight: 500, border: "1px solid var(--line)", cursor: "pointer", flexShrink: 0 };
export const btnAdicionar: CSSProperties = { marginTop: 14, width: "100%", height: 48, borderRadius: 12, border: "1px dashed var(--cool)", background: "var(--cool-wash)", color: "var(--cool-deep)", fontSize: 14.5, fontWeight: 600, cursor: "pointer" };
export const abaAmbiente: CSSProperties = { padding: "8px 14px", borderRadius: 100, border: "1px solid var(--line)", background: "var(--surface)", color: "var(--ink-soft)", fontSize: 13.5, fontWeight: 500, cursor: "pointer", whiteSpace: "nowrap" };
export const abaAmbienteOn: CSSProperties = { border: "1px solid var(--cool)", background: "var(--cool-wash)", color: "var(--cool-deep)", fontWeight: 600 };
export const btuBox: CSSProperties = { marginTop: 20, padding: "18px 22px", borderRadius: 14, background: "var(--cool-wash)", border: "1px solid var(--line)" };
export const prodCard: CSSProperties = { position: "relative", display: "flex", flexDirection: "column", gap: 6, padding: 14, borderRadius: 14, border: "1px solid var(--line)", background: "var(--surface)", cursor: "pointer", textAlign: "left" };
export const prodCardSel: CSSProperties = { border: "1px solid var(--cool)", boxShadow: "inset 0 0 0 1px var(--cool)" };
export const badgeRec: CSSProperties = { position: "absolute", top: 10, right: 10, fontSize: 10, fontFamily: mono, textTransform: "uppercase", letterSpacing: "0.05em", padding: "3px 8px", borderRadius: 100, background: "var(--cool)", color: "#fff" };
export const resumo: CSSProperties = { padding: "18px 22px", borderRadius: 14, background: "var(--surface)", border: "1px solid var(--line)" };
export const carrinhoItem: CSSProperties = { display: "flex", gap: 14, padding: 16, borderRadius: 14, border: "1px solid var(--line)", background: "var(--surface)", alignItems: "center" };
export const linkBtn: CSSProperties = { background: "none", border: "none", padding: 0, color: "var(--cool)", fontSize: 12.5, fontWeight: 600, cursor: "pointer" };
export const barraCarrinho: CSSProperties = { position: "fixed", left: 0, right: 0, bottom: 0, zIndex: 20, display: "flex", justifyContent: "center", padding: "0 16px 16px" };
export const barraCarrinhoInner: CSSProperties = { width: "100%", maxWidth: 760, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 14, padding: "14px 20px", borderRadius: 14, background: "var(--ink)", color: "#fff", boxShadow: "0 8px 24px rgba(0,0,0,0.25)", cursor: "pointer", border: "none" };
export const btnPrimary: CSSProperties = { height: 46, padding: "0 22px", borderRadius: 10, background: "var(--cool)", color: "#fff", fontWeight: 600, fontSize: 15, border: "none", cursor: "pointer", textDecoration: "none", display: "inline-flex", alignItems: "center", justifyContent: "center" };
export const btnGhost: CSSProperties = { height: 46, padding: "0 20px", borderRadius: 10, background: "var(--surface)", color: "var(--ink-soft)", fontWeight: 600, fontSize: 15, border: "1px solid var(--line)", cursor: "pointer" };
